#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2013 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

set -e

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.locales=*|locales=*)
				LIVE_LOCALES="${_PARAMETER#*locales=}"
				;;
		esac
	done
}

ConfigureLocales ()
{	
	echo -n " locales and keyboard"

	setkeyboard=${LIVE_LOCALES%%_*}

	echo \
"#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

update-locale LANG=${LIVE_LOCALES} LANGUAGE=${LIVE_LOCALES} LC_CTYPE=${LIVE_LOCALES}

# Checking if locales-all is installed
if [ -d /usr/share/doc/locales-all ]; then
	update-locale LC_ALL=${LIVE_LOCALES}
fi

source /etc/default/locale

exit 0
" > /etc/rc.local

}

Cmdline
ConfigureLocales
