#!/usr/bin/env zsh
# Copyright (c) 2016-2017 Dyne.org Foundation
# libdevuansdk is maintained by Ivan J. <parazyd@dyne.org>
#
# This file is part of libdevuansdk
#
# This source code is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this source code. If not, see <http://www.gnu.org/licenses/>.

## all windows users are suckers

build_kernel_${arch}() {
	fn build_kernel_${arch} "(override)"
	req=(strapdir arch abiname flavor)
	ckreq || return 1
	
	kernel_options=(
		linux-image-${abiname}-${flavor}
		linux-image-${abiname}-${flavor}-gnu
		linux-image-${abiname}-${flavor}-libre
		linux-image-${abiname}-${flavor}-unsigned	
	)
	
	notice "installing stock kernel for $arch"

	cat <<EOF | sudo tee ${strapdir}/install-linux
#!/bin/sh
apt-get update
allpkgs="\$(apt-cache search '.' | cut -d' ' -f1)"

for i in ${kernel_options} ; do
	for j in \`printf "%s" "\${allpkgs}" | grep "^\$i$"\`; do
		if [ -z "\${ker}" ]; then
			ker="\$j"
		fi
	done
done

apt-get --yes --allow-unauthenticated install \${ker}
apt-get --yes --allow-remove-essential autoremove
apt-get clean
EOF

	chroot-script -d install-linux || zerr
}
