#!/usr/bin/env zsh
# Copyright (c) 2016-2018 Dyne.org Foundation
# libdevuansdk is maintained by Ivan J. <parazyd@dyne.org>
#
# This file is part of libdevuansdk
#
# This source code is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this source code. If not, see <http://www.gnu.org/licenses/>.

## default system configurations

conf_print_debconf() {
	fn conf_print_debconf $*
	local _lang="$1"
	req=(_lang)

	cat <<EOF
#!/bin/sh
apt-get update
apt-get --yes --allow-unauthenticated install locales
sed -e 's/# ${_lang} UTF-8/${_lang} UTF-8/' -i /etc/locale.gen
locale-gen
update-locale LANG=${_lang} LANGUAGE=${_lang} LC_CTYPE=${_lang} LC_MESSAGES=${_lang}
dpkg-query -l locales-all > /dev/null 2>&1
if [ "$?" -eq 0 ]; then
	update-locale LC_ALL=${_lang}
fi
set -o allexport
. /etc/default/locale
set +o allexport
apt-get --yes --allow-unauthenticated dist-upgrade
apt-get clean
EOF
}

conf_print_hostname() {
	fn conf_print_hostname
	req=(os)
	ckreq || return 1

	print $os
}

conf_print_hosts() {
	fn conf_print_hosts
	req=(os)
	ckreq || return 1

	cat <<EOF
127.0.0.1        ${os}                localhost
::1              ip6-localhost ip6-loopback
fe00::0          ip6-localnet
fe00::0          ip6-mcastprefix
fe02::1          ip6-allnodes
fe02::1          ip6-allrouters
EOF
}

conf_print_resolvconf() {
	fn conf_print_resolvconf "(override)"
	
	cat <<EOF
## google's nameservers
nameserver 8.8.8.8
nameserver 8.8.4.4
EOF
}

conf_print_sourceslist() {
	fn conf_print_sourceslist "(override)"
	req=(mirror release section suite)
	ckreq || return 1

	[[ $APT_CACHE = 1 ]] && {
		cat <<EOF
deb file:/mnt ./

EOF
	}

	cat <<EOF
deb ${mirror} ${release} ${section}
deb-src ${mirror} ${release} ${section}

EOF

	[[ $suite != "unstable" ]] && {
		cat <<EOF
deb ${mirror} ${release}-updates ${section}
deb-src ${mirror} ${release}-updates ${section}

EOF
	}

	[[ $suite = "stable" ]] && {
		cat <<EOF
deb ${mirror} ${release}-security ${section}
deb-src ${mirror} ${release}-security ${section}

EOF
	}

	[[ $PROPOSED_UPDATES = 1 ]] && {
		cat <<EOF
deb ${mirror} ${release}-proposed-updates ${section}

EOF
	}

}
