#!/usr/bin/env zsh
# star-openbox.blend

core_packages+=(
	
	# btrfs-progs
	# reiserfsprogs 
	# reiser4progs
	nfs-common
	dosfstools
	mtools
	ntfs-3g
	xfsprogs
	xfsdump 
 	jfsutils 		
	gpart
	live-tools
	eject
	file
	
)

base_packages+=(

	user-setup
	win32-loader
	aptitude
	mawk
	ntp
	dialog
	# os-prober
	ifupdown
	isc-dhcp-client
	debconf
	# acpi-support-base
	apt-listchanges
	dnsutils
	# ftp
	iw
	# laptop-detect
# 	reportbug
	usbutils
	whois
	net-tools
	psmisc
	wpasupplicant
	iputils-ping
	bind9-host
	traceroute
# 	ethtool
	gawk
	hwinfo
	wget
	gettext-base
	
)

extra_packages+=(	
	
	xorg
	accountsservice
	apparmor
	upower
	slim
	pm-utils
	hwdata
	xdg-user-dirs
	xdg-utils
	alsa-utils
	apulse
	rtkit
	tasksel
	gamin
	cpufrequtils
	tzdata
	unrar
	unzip
	lzop
	zip
	xz-utils
	gzip
	rpl
	logrotate
	mpg321
	gstreamer1.0-plugins-base
	gstreamer1.0-plugins-good 
	gstreamer1.0-plugins-bad
	gstreamer1.0-plugins-ugly
	gstreamer1.0-alsa
	gir1.2-gst-plugins-base-1.0
	gir1.2-gstreamer-1.0
	libpolkit-gobject-consolekit-1-0
	libpolkit-backend-consolekit-1-0
	libpolkit-backend-1-0
	consolekit
	policykit-1
	policykit-1-gnome
	rfkill
	usbutils
	localepurge
	xserver-xorg-video-all
	intel-microcode
	amd64-microcode
	iucode-tool
	firmware-linux-nonfree
	firmware-zd1211
	firmware-netxen
	firmware-ralink 
	firmware-iwlwifi
	firmware-intelwimax 
	firmware-brcm80211
	firmware-realtek
	firmware-atheros
	firmware-libertas
	firmware-bnx2
	firmware-b43-installer 
	firmware-b43legacy-installer 
	b43-fwcutter 
	mobile-broadband-provider-info 
	wireless-tools
	wireless-regdb
	crda
	lsb-release
	wmctrl
	apt-transport-https
	desktop-base
	bash-completion
	ttf-dejavu 
	fonts-liberation 
	fontconfig-config 
	dmz-cursor-theme
	gtk2-engines-murrine 
	gtk2-engines-pixbuf
	hdparm 
	disk-manager 
	ufw 
	gparted  
	htop
	hardinfo 
	synaptic
	i3lock
	suckless-tools 
	epiphany-browser
	conky-all 
	scrot
	xpdf
	xterm
	ncdu
	pciutils
	task-english
	# kexec-tools
	dunst
	connman
	connman-ui
	hsetroot
	arandr
	lxappearance
	lxterminal
	mirage
	mousepad
	pcmanfm
	libfm-modules
	lsof
	# spacefm
	# udevil
	yad
	mpv
	pmount
	xarchiver
	libnotify-bin
	cryptsetup-run
	cryptsetup-initramfs
	# haveged
	# galternatives
	# libsox-fmt-all
	# inxi
	# linux-headers-${arch}
	

)

extra_packages+=(	
	
	openbox
	obconf
	obmenu
	tint2

)

purge_packages+=(

	lm-sensors
	obsession
	ofono
	aptitude
	aptitude-common
	avahi-daemon
	cups-bsd
	cups-client
	cups-common
	debian-keyring
	elogind
	enchant
	evince
	fonts-droid-fallback
	fonts-noto-mono
	javascript-common
	ncurses-term
	manpages
	manpages-dev
	p7zip-full
	poppler-data
	poppler-utils
	publicsuffix
	yelp
	yelp-xsl

)	

[[ ($release = "jessie") || ($release = "ascii") ]] && extra_packages+=(

 	gksu
		
)
